### ISSUE TITLE
user process caused "exec format error"

### ISSUE THREAD

**Issue by kierendev** [mikesir87/aws-cli-docker#10]
`standard_init_linux.go:190: exec user process caused "exec format error"`

This error is coming up when trying to use this image on the latest build?

**Comment by kierendev** [comment]
Doesn't happen with previous build (1.15.85)

**Comment by mikesir87** [comment]
Interesting. Can you share an example command to reproduce the error you’re seeing?

**Comment by stayallive** [comment]
I am running into the same thing with the following command:

```
aws s3 cp "public/" "s3://xxx/yarn/${DRONE_COMMIT}/" --recursive --exclude "*" --include "mix-manifest.json" --include "build/*" --no-progress
```

With the following env variables (which I validated are all set):

```
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: xxx
```

Went back to version `1.16.170` and no issues anymore.

**Comment by mikesir87** [comment]
Interesting... starting with `1.16.171`, I started pushing multi-arch images (amd64 and arm64). What version of the Docker engine are you running?

**Comment by mikesir87** [comment]
Ok. I've been able to reproduce using a machine with 18.09.4 (I'm running the 19.03 beta locally). I rebuilt the image using the built-in builder (not using the `buildx` plugin to support multi-arch images) and pushed it. Verified it's working on the 18.09.4 machine.

Can you give it a shot now?

**Comment by madve2** [comment]
I also had the `"exec format error"` issue earlier today (which I worked around by temporarily using `1.16.170`, as suggested above), and I can confirm that `latest` is working again, I have just tried it in my pipeline. Thank you for reacting so quickly :)

**Comment by mikesir87** [comment]
Great! Happy to help!

I'll have to do some more research to figure exactly what was causing it to break, as nothing _should_ have broken. 🤷‍♂ I had noticed looking at one of the image histories that the timestamp for one layer was 200+ years ago. So... something happened, just not sure what. And now the weird part is I can't reproduce it since pushing the fixed version (even when loading the image using its digest). 🤔 

Anywho... glad to hear it's working again!

**Comment by kierendev** [comment]
Glad to see this was fixed so fast! Thank you!
