### ISSUE TITLE
Release 2.0.0 Build Failing

### ISSUE THREAD

**Issue by lawsonAGMT** [mikesir87/aws-cli-docker#13]

**Comment by mikesir87** [comment]
Thanks @lawsonAGMT! I had made the mistake of assuming that the v2 cli was still going through pip/python, but nope! Will be making updates to it today and getting that working again. Sorry for the inconvenience!

**Comment by mikesir87** [comment]
It took a little longer, but have the `:latest` and `:v2` tags now building the v2 cli correctly! Feel free to give it a shot and let me know how it goes!
