### ISSUE TITLE
Install wget in this image

### ISSUE THREAD

**Issue by pgbezerra** [mikesir87/aws-cli-docker#14]
Before Debian image change, this docker image had `wget`.
I think that deserves to keep this program in your image.

Thank you!

**Comment by mikesir87** [comment]
Ok! I'm happy to add it back in. That was just coincidence, since alpine has `wget` by default. The change to debian is because the aws-cli v2 is built using glibc, so doesn't work in alpine-based images as of right now.

**Comment by mikesir87** [comment]
Merged and should be deployed shortly (auto-builds sometimes take several minutes)

**Comment by pgbezerra** [comment]
Thank you very much!!

**Comment by G-Rath** [comment]
@mikesir87 it seems that `xxd` also didn't make it into v2, which I currently use for my lambda deploys:

> CODESHA256=`sha256sum build/${AWS_FUNCTION_NAME}.zip | head -c 64 | xxd -r -p | base64`

Should I open a new issue (or better yet make a PR adding it to the installed things)?

**Comment by mikesir87** [comment]
Feel free to make a PR @G-Rath!
