### ISSUE TITLE
add unzip to v2

### ISSUE THREAD

**Issue by adrianomitre** [mikesir87/aws-cli-docker#16]
The tool `unzip` was removed -- non-intentionally, I guess --  from v2.

Contrast this
```sh
$ docker run -it mikesir87/aws-cli:v1
/aws # unzip
BusyBox v1.31.1 () multi-call binary.

Usage: unzip [-lnojpq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]

Extract FILEs from ZIP archive

	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-j	Do not restore paths
	-p	Print to stdout
	-q	Quiet
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
```
to this ([`2.0.6/v2/latest`](https://github.com/mikesir87/aws-cli-docker/commit/40d52a007b2e2802d68879faa6cfb9afcf37f579) as of now)
```sh
$ docker run -it mikesir87/aws-cli:v2
root@a93ba6fa2b39:/aws# unzip
bash: unzip: command not found
```

**Comment by mikesir87** [comment]
Yup. Another unintentional drop in the change from alpine to Debian (since v2 requires glibc right now). Looks like I need to do a full diff of commands to see what else might be missing too!

**Comment by adrianomitre** [comment]
Would you please let me know when you release 2.0.7?

**Comment by mikesir87** [comment]
2.0.7 hasn’t been released yet by AWS. I did rebuild and refuse the v2 and latest tags. Once 2.0.7 is released, I’ll push it. 👍
