### ISSUE TITLE
No tag for version 1.14.9

### ISSUE THREAD

**Issue by stefanbirkner** [mikesir87/aws-cli-docker#3]
The version 1.14.9 of the image is only available with the tag latest but not with the tag 1.14.9. See https://hub.docker.com/r/mikesir87/aws-cli/tags/

**Comment by mikesir87** [comment]
Sorry about that! It looks like the automated build failed for an "Unexpected error."  Just retriggered the build, so should be out here shortly! 👍

**Comment by mikesir87** [comment]
Ok. 1.14.9 tag is now available. In addition, I've updated latest to 1.14.10 and created the 1.14.10 tag too.

**Comment by stefanbirkner** [comment]
Thanks for the fix.
