### ISSUE TITLE
Not able to upload on s3 bucket

### ISSUE THREAD

**Issue by pkhetan** [mikesir87/aws-cli-docker#4]
Hi,
I am trying to upload some files from my docker container to s3 bucket which is managed by rook. But while uploading it is not able to detect exact path for the object.

docker run --env AWS_ACCESS_KEY_ID=xyz --env AWS_SECRET_ACCESS_KEY=abc mikesir87/aws-cli aws --endpoint-url https://s3.company.com --no-verify-ssl s3 cp filename.txt s3://teamfelgen/test/

Result
The user-provided path filename.txt does not exist.

But I am in the same folder where this file is present.
Also I tried to put exact path from home directory like
~/piyush/filename.txt
/piyush/filename.txt

Note: Same command with aws cli is working as expected
aws --endpoint-url https://s3.company.com --no-verify-ssl s3 cp filename.txt s3://teamfelgen/test/

**Comment by mikesir87** [comment]
Hi @pkhetan! You’re seeing that problem because the file isn’t Avila me inside the container. So, to solve it, mount the current directory into the container. Using the `-v` option. Here’s an example...

```
docker run -v $(pwd):/app --env AWS_ACCESS_KEY_ID=xyz --env AWS_SECRET_ACCESS_KEY=abc mikesir87/aws-cli aws --endpoint-url https://s3.company.com --no-verify-ssl s3 cp filename.txt s3://teamfelgen/test/
```

**Comment by pkhetan** [comment]
I am getting the same error. Do I need to replace anything or keep it exactly same. 
"-v $(pwd):/app"

**Comment by mikesir87** [comment]
Should be able to keep it the same. Try adjusting the cp to use `/app/filename.txt`, as that’s where the mount is.

**Comment by pkhetan** [comment]
Got it exactly like I wanted. Thanks a lot!

**Comment by mikesir87** [comment]
Ah! Remembered the default working directory wrong. If you adjust the mount to `$(pwd):/AWS`, then you don’t have to adjust the file path in the cp command. Sorry about that!

**Comment by pkhetan** [comment]
What about windows. How do we mount on windows.

**Comment by mikesir87** [comment]
Good question! I haven't tried it (as I don't have a Windows machine), but based on the link below, it looks like the mount spec above should still work on Windows. Note that the image isn't multi-architecture, so would have to run in a similar way as other Linux-based containers on Windows.

https://stackoverflow.com/a/41489151/502139

**Comment by mikesir87** [comment]
Going to close as this has been hanging around for a while and I successfully upload via S3 quite often. Feel free to reopen if you're still having issues.

**Comment by javen23** [comment]
ver video: https://www.youtube.com/watch?v=9NhnOlE8fa8
Deployment de una aplicación en React utilizando Amazon S3 (Integración con Github) #5
