### ISSUE TITLE
Problem with configure command in documentation, returns EOF

### ISSUE THREAD

**Issue by mb16** [mikesir87/aws-cli-docker#5]
I ran the configure command in your documentation:

`docker run --rm -v $HOME/.aws:/root/.aws mikesir87/aws-cli aws configure`

and received the following error: EOF when reading a line.  This was done on a Mac in a bash terminal.
The solution was to add a "ti" switch.

`docker run --rm -tiv $HOME/.aws:/root/.aws mikesir87/aws-cli aws configure`

Please add a note in your documentation for others who might encounter this error.

**Comment by mikesir87** [comment]
Ah! Good catch! I’m on the road right now, but feel free to send a PR to fix it if you’d like. 😁

**Comment by mikesir87** [comment]
Resolved with f9df4ca29b4dd91b021386d9d8900ccaeeca95a7
